name: Tasmota Docker test

on:
  push:
  workflow_dispatch:  # Manually start a workflow

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Docker container
        run: docker build -t docker-tasmota .
      - name: Clone Tasmota repo
        run: git clone https://github.com/arendst/Tasmota.git
      - name: Build a firmware
        run: bash ./compile.sh tasmota tasmota32
